import axios from "axios";
import { ExportToCsv } from "export-to-csv";

export default function downloadSpecies() {
  const species = axios
    .get(`api/getspecies`)
    .then(function (response) {
      console.log("GOT SPECIES", response.data);
      return response.data;
    })
    .catch(function (error) {
      console.log(error);
    });
  const options = {
    filename: "generated_species_list",
    fieldSeparator: ",",
    quoteStrings: '"',
    decimalSeparator: ".",
    showLabels: true,
    showTitle: true,
    title: "Species List Generated by eBirdCBC",
    useTextFile: false,
    useBom: true,
    useKeysAsHeaders: true,
  };
    const csvExporter = new ExportToCsv(options);
    csvExporter.generateCsv(species);
}
